M48
; DRILL file {KiCad 7.0.1-3b83917a11~172~ubuntu22.04.1} date Mon 25 Nov 2024 12:37:49 PM CST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-11-25T12:37:49-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1-3b83917a11~172~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X5.4Y-5.5
X7.4Y-5.5
T0
M30
